DROP PROCEDURE IF EXISTS COUNT_PRODUCT_SALES
GO

CREATE PROCEDURE COUNT_PRODUCT_SALES @PDays INT AS
BEGIN
    BEGIN TRY
        SELECT Count(SALEID) FROM SALE WHERE DATEDIFF(day, SALEDATE, GETDATE()) >= @PDays
    END TRY
    BEGIN CATCH
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1
        END;
    END CATCH

END
GO

EXEC COUNT_PRODUCT_SALES @PDays = 5;