DROP PROCEDURE IF EXISTS DELETE_CUSTOMER;
GO

CREATE PROCEDURE DELETE_CUSTOMER @PCUSTID int AS
BEGIN
    BEGIN TRY
    DECLARE @SCUSTID int = (SELECT CUSTID FROM SALE WHERE CUSTID = @PCUSTID)


        IF @PCUSTID IS NULL
            THROW 50290, 'Customer ID not found', 1
        ELSE IF @PCUSTID = @SCUSTID
            THROW 50300, 'Customer cannot be deleted as sales exist.', 1

        DELETE FROM CUSTOMER WHERE @PCUSTID = CUSTID;

    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1;
    END CATCH;


END
GO




SELECT *
FROM CUSTOMER;

EXEC DELETE_CUSTOMER @PCUSTID = 1;

SELECT *
FROM CUSTOMER;