DROP FUNCTION IF EXISTS DELETE_ALL_CUSTOMERS;
GO

CREATE FUNCTION DELETE_ALL_CUSTOMERS (@Count INT) RETURNS INT AS 
BEGIN
    -- DROP TABLE IF EXISTS @Deleted;
    -- DECLARE @Deleted TABLE(CUSTID INT, CUSTNAME	NVARCHAR(100), SALES_YTD INT, STATUS NVARCHAR(7));
    DELETE FROM CUSTOMER;
    DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
    THROW 50000, @ERRORMESSAGE, 1;


    RETURN CONCAT("test", @Count);
END;
GO

SELECT *
FROM CUSTOMER;

EXEC DELETE_ALL_CUSTOMERS;

SELECT *
FROM CUSTOMER;