DROP PROCEDURE IF EXISTS DELETE_ALL_CUSTOMER;
GO

CREATE PROCEDURE DELETE_ALL_CUSTOMER AS
BEGIN
    BEGIN TRY
            DELETE FROM CUSTOMER;
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1;
    END CATCH;
END;
GO;


DROP FUNCTION IF EXISTS DELETE_ALL_CUSTOMERS;
GO

CREATE FUNCTION DELETE_ALL_CUSTOMERS (@numRows INT) RETURNS INT AS 
BEGIN
    Select @numRows = Count(*) FROM CUSTOMER
    RETURN @numRows
END;
GO



SELECT *
FROM CUSTOMER;

BEGIN
    Select dbo.DELETE_ALL_CUSTOMERS(1);
END

EXEC dbo.DELETE_ALL_CUSTOMER;

SELECT *
FROM CUSTOMER;