DROP PROCEDURE IF EXISTS DELETE_ALL_SALES
GO

CREATE PROCEDURE DELETE_ALL_SALES AS
BEGIN
    BEGIN TRY
        DELETE FROM SALE;
        
        UPDATE CUSTOMER
        SET SALES_YTD = 0;
        UPDATE PRODUCT
        SET SALES_YTD = 0; 
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1;
    END CATCH;
END
GO


SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCT;
SELECT * FROM SALE;
GO
EXEC DELETE_ALL_SALES;
GO
SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCT;
SELECT * FROM SALE;