DROP PROCEDURE IF EXISTS DELETE_ALL_PRODUCT_FROM_DB;
GO

CREATE PROCEDURE DELETE_ALL_PRODUCT_FROM_DB AS
BEGIN
    BEGIN TRY
            DELETE FROM PRODUCT;
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1;
    END CATCH;
END;
GO;


DROP FUNCTION IF EXISTS DELETE_ALL_PRODUCTS_FROM_DB;
GO

CREATE FUNCTION DELETE_ALL_PRODUCTS_FROM_DB (@numRows INT) RETURNS INT AS 
BEGIN
    Select @numRows = Count(*) FROM PRODUCT
    RETURN @numRows
END;
GO

Select * FROM PRODUCT;
BEGIN
    SELECT dbo.DELETE_ALL_PRODUCTS_FROM_DB(1);
END
GO

EXEC DELETE_ALL_PRODUCT_FROM_DB;
GO

Select * FROM PRODUCT;
