DROP PROCEDURE IF EXISTS DELETE_SALE;
GO

CREATE PROCEDURE DELETE_SALE AS
BEGIN
    BEGIN TRY
    DECLARE @SALEID bigint = (SELECT MIN(SALEID) FROM SALE)
    DECLARE @SCust int = (SELECT CUSTID FROM SALE WHERE @SALEID = SALEID)
    DECLARE @SProd int = (SELECT PRODID FROM SALE WHERE @SALEID = SALEID)
    DECLARE @SPAMT int = (SELECT (PRICE * QTY) FROM SALE WHERE @SALEID = SALEID)
    SELECT MIN(SALEID) FROM SALE;

        IF @SALEID IS NULL
            THROW 50280, 'No Sale Rows Found', 1;

        DELETE FROM SALE WHERE @SALEID = SALEID;

        EXEC UPD_CUST_SALESYTD @PCUSTID = @SCust, @PAMT = @SPAMT;
        EXEC UPD_PROD_SALESYTD @PPRODID = @SProd, @PAMT = @SPAMT;
        
    END TRY
    BEGIN CATCH

        IF ERROR_NUMBER() = 50280
            THROW
        ELSE
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1;
        END
    END CATCH;



END
GO




SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCT;
SELECT * FROM SALE;

EXEC DELETE_SALE;

SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCT;
SELECT * FROM SALE;