DROP PROCEDURE IF EXISTS DELETE_PRODUCT;
GO

CREATE PROCEDURE DELETE_PRODUCT @PPRODID int AS
BEGIN
    BEGIN TRY
    DECLARE @SPRODID int = (SELECT PRODID FROM SALE WHERE PRODID = @PPRODID)


        IF @PPRODID IS NULL
            THROW 50310, 'Product ID not found', 1
        ELSE IF @PPRODID = @SPRODID
            THROW 50320, 'Product cannot be deleted as sales exist.', 1

        DELETE FROM PRODUCT WHERE @PPRODID = PRODID;

    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 50310
            THROW
        ELSE IF ERROR_NUMBER() = 50320
            THROW
        ELSE
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1;
        END
    END CATCH;


END
GO




SELECT *
FROM PRODUCT;

EXEC DELETE_PRODUCT @PPRODID = 1706;

SELECT *
FROM PRODUCT;