DROP PROCEDURE IF EXISTS GET_PROD_STRING;
GO

CREATE PROCEDURE GET_PROD_STRING @PPRODID INT AS
BEGIN
    BEGIN TRY
        IF (@PPRODID IS NULL)
        THROW 50090, 'Product ID not found', 1
    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 50090
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END; 
    END CATCH

END;
GO

DROP FUNCTION IF EXISTS dbo.GET_PROD_STRINGS;
GO

CREATE FUNCTION GET_PROD_STRINGS (@PPRODID INT) RETURNS NVARCHAR(MAX) AS
BEGIN
    RETURN CONCAT('Prodid: ', (@PPRODID ), ' Name: ', (Select PRODNAME FROM PRODUCT Where @PPRODID = PRODID), ' Price: ', (Select SELLING_PRICE FROM PRODUCT Where @PPRODID = PRODID), ' SalesYTD: ', (Select SALES_YTD FROM PRODUCT Where @PPRODID = PRODID));
END
GO


-- BEGIN
--     SELECT dbo.GET_CUSTOMER_STRING;
-- END;


BEGIN
    SELECT dbo.GET_PROD_STRINGS(1000)
    EXEC GET_PROD_STRING @PPRODID = 9000;
END