DROP PROCEDURE IF EXISTS GET_ALL_CUSTOMERS
GO

CREATE PROCEDURE GET_ALL_CUSTOMERS AS
BEGIN
    BEGIN TRY
        DECLARE @CUSTOMER CURSOR SELECT * FROM CUSTOMER
    END TRY
    BEGIN CATCH
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1;
        END
    END CATCH
    OUTPUT @CUSTOMER.*;
END
GO

EXEC GET_ALL_CUSTOMERS

-- DECLARE @MyCursor CURSOR;
-- EXEC GET_ALL_CUSTOMERS @CustomerCursor = @MyCursor OUTPUT;
-- WHILE (@@FETCH_STATUS = 0)  
-- BEGIN;  
--      FETCH NEXT FROM @MyCursor;  
-- END;  
-- CLOSE @MyCursor;  
-- DEALLOCATE @MyCursor;  
-- GO
