DROP PROCEDURE IF EXISTS GET_ALL_CUSTOMERS
GO

CREATE PROCEDURE GET_ALL_CUSTOMERS @POUTCUR CURSOR VARYING OUTPUT AS
BEGIN
    BEGIN TRY
       SET @POUTCUR = CURSOR FOR SELECT * FROM CUSTOMER;
       OPEN @POUTCUR;
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END;
GO



BEGIN
    DECLARE @CUR CURSOR
    EXEC GET_ALL_CUSTOMERS @POUTCUR = @CUR OUTPUT;

    DECLARE @CUSTID INT,
            @CUSTNAME NVARCHAR(100),
            @SALES_YTD INT,
            @STATUS NVARCHAR(7);

    FETCH NEXT FROM @CUR INTO @CUSTID, @CUSTNAME, @SALES_YTD, @STATUS;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        PRINT(CONCAT('ID: ', @CUSTID, ' Name: ', @CUSTNAME, ' Total Sales: ', @SALES_YTD, ' STATUS: ', @STATUS))
        FETCH NEXT FROM @CUR INTO @CUSTID, @CUSTNAME, @SALES_YTD, @STATUS;
    END;
    CLOSE @CUR;
    DEALLOCATE @CUR;
END;