DROP PROCEDURE IF EXISTS GET_CUSTOMER_STRING;
GO

CREATE PROCEDURE GET_CUSTOMER_STRING @PCUSTID INT AS
BEGIN
    BEGIN TRY
        IF (@PCUSTID < 1 OR @PCUSTID > 499)
        THROW 50020, 'Customer ID out of range', 1
    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 50020
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END; 
    END CATCH

END;
GO

DROP FUNCTION IF EXISTS dbo.GET_CUSTOMER_STRINGS;
GO

CREATE FUNCTION GET_CUSTOMER_STRINGS (@PCUSTID INT) RETURNS NVARCHAR(MAX) AS
BEGIN
    RETURN CONCAT('CustID: ', (@PCUSTID ), ' Name: ', (Select * FROM CUSTOMER Where @PCUSTID = CUSTID));
END
GO


-- BEGIN
--     SELECT dbo.GET_CUSTOMER_STRING;
-- END;


BEGIN
    SELECT dbo.GET_CUSTOMER_STRINGS(1)
END