DROP PROCEDURE IF EXISTS GET_ALL_PRODUCTS
GO

CREATE PROCEDURE GET_ALL_PRODUCTS AS
BEGIN
    DECLARE @cur_PRODID INT
    DECLARE @cur_PRODNAME NVARCHAR
    DECLARE @cur_SELLING_PRICE MONEY
    DECLARE @cur_SALES_YTD MONEY
    DECLARE @SQL nvarchar(max)

    DECLARE PRODUCT_CURSOR CURSOR FAST_FORWARD
    FOR
    SELECT PRODID, PRODNAME, SELLING_PRICE, SALES_YTD FROM dbo.PRODUCT

    OPEN PRODUCT_CURSOR

    FETCH NEXT FROM PRODUCT_CURSOR into @cur_PRODID, @cur_PRODNAME, @cur_SELLING_PRICE, @cur_SALES_YTD

    WHILE @@FETCH_STATUS = 0

    BEGIN TRY
        return  @cur_PRODID
        EXEC SP_EXECUTESQL @SQL
        FETCH NEXT FROM PRODUCT_CURSOR INTO @cur_PRODID, @cur_PRODNAME, @cur_SELLING_PRICE, @cur_SALES_YTD
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH



END
GO
CLOSE PRODUCT_CURSOR;
DEALLOCATE PRODUCT_CURSOR;
GO


EXEC GET_ALL_PRODUCTS