DROP PROCEDURE IF EXISTS GET_ALL_CUSTOMERS
GO

CREATE PROCEDURE GET_ALL_CUSTOMERS AS
BEGIN
    DECLARE @cur_CUSTID INT
    DECLARE @cur_CUSTNAME NVARCHAR
    DECLARE @cur_SALES_YTD INT
    DECLARE @cur_STATUS NVARCHAR
    DECLARE @SQL nvarchar(max)

    DECLARE CUSTOMER_CURSOR CURSOR FAST_FORWARD
    FOR
    SELECT CUSTID, CUSTNAME, SALES_YTD, STATUS FROM dbo.CUSTOMER

    OPEN CUSTOMER_CURSOR

    FETCH NEXT FROM CUSTOMER_CURSOR into @cur_CUSTID, @cur_CUSTNAME, @cur_SALES_YTD, @cur_STATUS

    WHILE @@FETCH_STATUS = 0

    BEGIN TRY
        return  @cur_CUSTID
        EXEC SP_EXECUTESQL @SQL
        FETCH NEXT FROM CUSTOMER_CURSOR INTO @cur_CUSTID, @cur_CUSTNAME, @cur_SALES_YTD, @cur_STATUS
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH

END
GO
CLOSE CUSTOMER_CURSOR;
DEALLOCATE CUSTOMER_CURSOR;
GO


EXEC GET_ALL_CUSTOMERS