DROP FUNCTION IF EXISTS GET_CUSTOMER_STRING;
GO

CREATE FUNCTION GET_CUSTOMER_STRING (@PCUSTID INT) RETURNS TABLE AS
BEGIN
    RETURN CONCAT();
END;
GO

-- BEGIN
--     SELECT dbo.GET_CUSTOMER_STRING;
-- END;



BEGIN
    SELECT dbo.GET_CUSTOMER_STRING(1)
END;