DROP PROCEDURE IF EXISTS GET_ALLSALES
GO

CREATE PROCEDURE GET_ALLSALES @POUTCUR CURSOR VARYING OUTPUT AS
BEGIN
    BEGIN TRY
       SET @POUTCUR = CURSOR FOR SELECT * FROM SALE;
       OPEN @POUTCUR;
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END;
GO



BEGIN
    DECLARE @CUR CURSOR
    EXEC GET_ALLSALES @POUTCUR = @CUR OUTPUT;

    DECLARE @SALEID BIGINT,
            @CUSTID INT,
            @PRODID INT,
            @QTY INT,
            @PRICE MONEY,
            @SALEDATE DATE;

    FETCH NEXT FROM @CUR INTO @SALEID, @CUSTID, @PRODID, @QTY, @PRICE, @SALEDATE;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        PRINT(CONCAT('ID: ', @SALEID, ' CUSTOMER ID: ', @CUSTID, ' PRODUCT ID: ', @PRODID, ' QTY: ', @QTY, ' PRICE: ', @PRICE, ' Date of Sale: ', @SALEDATE))
        FETCH NEXT FROM @CUR INTO @SALEID, @CUSTID, @PRODID, @QTY, @PRICE, @SALEDATE;
    END;
    CLOSE @CUR;
    DEALLOCATE @CUR;
END;