DROP PROCEDURE IF EXISTS SUM_PRODUCT_SALESYTD
GO

CREATE PROCEDURE SUM_PRODUCT_SALESYTD AS
BEGIN
    BEGIN TRY
        DECLARE @Total int = (SELECT Sum(SALES_YTD) FROM CUSTOMER);
    END TRY
    BEGIN CATCH
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1
        END;
    END CATCH
    -- DECLARE @SALESYTD MONEY = (SELECT )


    RETURN @Total
END
GO

EXEC SUM_PRODUCT_SALESYTD;

DROP FUNCTION IF EXISTS SUM_PRODUCT_SALESYTDD
GO

CREATE FUNCTION SUM_PRODUCT_SALESYTDD (@PPRODID INT) RETURNS INT AS
BEGIN
    DECLARE @Total INT = (SELECT SUM(SALES_YTD) FROM PRODUCT)
    Return @Total
END;
GO

SELECT * FROM PRODUCT

BEGIN
    SELECT dbo.SUM_PRODUCT_SALESYTDD(1000);
END