DROP PROCEDURE IF EXISTS UPD_CUSTOMER_STATUS;
GO

CREATE PROCEDURE UPD_CUSTOMER_STATUS @PCUSTID int, @PSTATUS NVARCHAR(7) AS

BEGIN
    BEGIN TRY

        IF (@PCUSTID IS NULL)
            THROW 50120, 'Customer ID not found.', 1
        ELSE IF ((LEN(@PSTATUS) > 7 AND LEN(@PSTATUS) < 2))
            THROW 50130, 'Invalid Status value.', 1

        UPDATE CUSTOMER
            SET STATUS = @PSTATUS
            WHERE CUSTID = @PCUSTID
    END TRY
    BEGIN CATCH

        IF ERROR_NUMBER() = 50120
            THROW
        ELSE IF ERROR_NUMBER() = 50130
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END;
    END CATCH;

END;
GO

SELECT * FROM CUSTOMER;

EXEC UPD_CUSTOMER_STATUS @PCUSTID = 3, @PSTATUS = 'SUSPEND';

SELECT * FROM CUSTOMER;